### ISSUE TITLE
There is a question about “rmmod: ERROR”.

### ISSUE THREAD

**Issue by jokervTv** [kinglongmee/rapoo-keyboard-driver#3]
when i run install-rapoo-keyboard-driver.sh, i see many errors.

rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'hid_rapoo': Operation not permitted
rmmod: ERROR: could not remove module hid-rapoo: Operation not permitted
rmmod: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'hid_generic': Operation not permitted
rmmod: ERROR: could not remove module hid-generic: Operation not permitted

I was so stupid that I don‘t what to do.

**Comment by kinglongmee** [comment]
You must run the install as root, or sudo. Otherwise, you are permitted.
