### ISSUE TITLE
make error on manjaro 17

### ISSUE THREAD

**Issue by xfans** [kinglongmee/rapoo-keyboard-driver#4]
make -C /lib/modules/4.9.44-1-MANJARO/build M=/data/soft/rapoo-keyboard-driver-1.1 modules
make[1]: 进入目录“/usr/lib/modules/4.9.44-1-MANJARO/build”
make[1]: *** 没有规则可制作目标“modules”。 停止。
make[1]: 离开目录“/usr/lib/modules/4.9.44-1-MANJARO/build”
make: *** [Makefile:25：default] 错误 2

**Comment by kinglongmee** [comment]
Do you install kernel-devel in your manjaro 17 system?

**Comment by xfans** [comment]
3Q Build Success.
Install [kernel-devel ](http://paperiniktips.sviluppo-siti-web.com/arch-linux-how-to-find-and-install-the-right-kernel-headers/)
